# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 5) do

  create_table "attribs", :force => true do |t|
    t.column "node_id", :integer, :null => false
    t.column "name",    :string,  :null => false
  end

  create_table "avalues", :force => true do |t|
    t.column "attrib_id", :integer, :null => false
    t.column "value",     :text,    :null => false
  end

  create_table "nodes", :force => true do |t|
    t.column "uuid",        :string, :limit => 38, :null => false
    t.column "description", :string
    t.column "notes",       :text
  end

  create_table "nodes_tags", :id => false, :force => true do |t|
    t.column "node_id", :integer, :null => false
    t.column "tag_id",  :integer, :null => false
  end

  add_index "nodes_tags", ["tag_id"], :name => "index_nodes_tags_on_tag_id"
  add_index "nodes_tags", ["node_id"], :name => "index_nodes_tags_on_node_id"

  create_table "tags", :force => true do |t|
    t.column "name", :string, :null => false
  end

end
